### ISSUE TITLE
ActiveJob

### ISSUE THREAD

**Issue by jnylen** [gevans/sidekiq-throttler#32]
How to use in ActiveJob?

**Comment by gevans** [comment]
I don't use Active Job but it looks like you can only specify extended options when using Sidekiq directly:

> Note that more advanced Sidekiq features (`sidekiq_options`) cannot be controlled or configured via ActiveJob, e.g. saving backtraces.

See the Sidekiq wiki on [Active Job](https://github.com/mperham/sidekiq/wiki/Active-Job).
